### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [timwmillard/uuid#1]
Dear @timwmillard, could you be so kind to compile `uuid.exe` for Windows 7 x64 (using @golang 1.20 perhaps)? I assume it's easier for you, the developer, to do this than it is for me, the user, who simply wants to learn more tagging things with UUIDs, not about the intricacies of compiling.

**Comment by timwmillard** [comment]
Yeah ok, I can create some pre build binaries for you.

**Comment by timwmillard** [comment]
I've create a release with pre-built binaries.  

https://github.com/timwmillard/uuid/releases/tag/v0.5.0

@sergeevabc download the [uuid_Windows_x86_64.zip](https://github.com/timwmillard/uuid/releases/download/v0.5.0/uuid_Windows_x86_64.zip) Window x64 version.

I do not have Windows, so I can not test this out.  I'm interested to know if it works ok.

**Comment by sergeevabc** [comment]
@timwmillard, it seems you've used @golang 1.22, but those traitors have recently cut off Windows 7 users like me, so the only way to go is to use 1.20.* to compile.

``` console
$ uuid.exe
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall(0x22fcf8)
        /opt/hostedtoolcache/go/1.22.0/x64/src/runtime/sys_windows_amd64.s:75 +0x7a fp=0x22fc80 sp=0x22fc60 pc=0x4686fa
rax     0x0
rbx     0x595a78
rcx     0x61a228
rdx     0x20
rdi     0x7fffffde000
rsi     0x22fe78
rbp     0x22fdc0
rsp     0x22fc58
r8      0x0
r9      0x22fee8
r10     0x6fa2e8
r11     0xc000004000
r12     0x22fec8
r13     0x0
r14     0x595100
r15     0x3
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b
```

**Comment by timwmillard** [comment]
@sergeevabc I've just done a new release using Go 1.20.14.

https://github.com/timwmillard/uuid/releases/tag/v0.5.1

I would be interested to see if that works.

**Comment by sergeevabc** [comment]
@timwmillard, it works as expected! Thank you for taking the time to make this app accessible to a wider audience that is looking for a way to create unique ids offline.

Things worth improving:
* add app's name and version to the help screen and a dedicated flag like `--version` to make it easier to understand what is used and when it's time to update
* add `(default)` next to `generate version 4`, because ids are so similar looking
* make the output more verbose either by default or by using a flag for the same aforementioned reason (e.g. `Generating 4 id(s) of UUID v7…`)

**Comment by timwmillard** [comment]
@sergeevabc , I'm glad it worked for you 😃.

Thank you for the feedback and suggestions.  I'll look to add them in the next release.

**Comment by sergeevabc** [comment]
> Thank you for the feedback and suggestions. I'll look to add them in the next release.

![blobgo](https://github.com/timwmillard/uuid/assets/373718/d9a41588-a8ad-4ec5-a8ad-108f88bd4322)
